// Auth
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// Hackathons
export const HACKATHONS_REQUESTED = 'HACKATHONS_REQUESTED';
export const HACKATHONS_RETRIEVED = 'HACKATHONS_RETRIEVED';
export const HACKATHONS_ERRORED = 'HACKATHONS_ERRORED';

export const HACKATHON_REQUESTED = 'HACKATHON_REQUESTED';
export const HACKATHON_RETRIEVED = 'HACKATHON_RETRIEVED';
export const HACKATHON_ERRORED = 'HACKATHON_ERRORED';

// Developers
export const TOP_DEVELOPERS_REQUESTED = 'TOP_DEVELOPERS_REQUESTED';
export const TOP_DEVELOPERS_RETRIEVED = 'TOP_DEVELOPERS_RETRIEVED';
export const TOP_DEVELOPERS_ERRORED = 'TOP_DEVELOPERS_ERRORED';
